version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myblog-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
    user: "www-data:www-data"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=blog
      - DB_USER=user
      - DB_PASSWORD=password
      - APP_ENV=development
      - APP_DEBUG=true

  db:
    image: mysql:8.0
    container_name: myblog-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
